# Generated by Django 4.1.7 on 2023-03-05 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("classes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Aprovacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("Aprovada", "Aprovada"), ("Reprovada", "Reprovada")],
                        max_length=10,
                    ),
                ),
                ("observacoes", models.TextField(blank=True)),
                (
                    "resposta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="classes.respostaatividade",
                    ),
                ),
            ],
        ),
    ]
