# Generated by Django 4.1.7 on 2023-03-06 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classes", "0003_alter_aprovacao_resposta"),
    ]

    operations = [
        migrations.AddField(
            model_name="respostaatividade",
            name="aprovacao",
            field=models.BooleanField(default=False),
        ),
    ]
