# Generated by Django 4.1.7 on 2023-03-10 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classes", "0005_alter_respostaatividade_aprovacao_delete_aprovacao"),
    ]

    operations = [
        migrations.AlterField(
            model_name="respostaatividade",
            name="aprovacao",
            field=models.CharField(
                choices=[("A", "Aprovado"), ("R", "Reprovado"), ("P", "Pendente")],
                default="P",
                max_length=1,
            ),
        ),
    ]
