# Generated by Django 4.1.7 on 2023-03-21 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("classes", "0011_remove_atividade_turma"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="professores",
            name="turma",
        ),
        migrations.RemoveField(
            model_name="professores",
            name="user",
        ),
        migrations.DeleteModel(
            name="alunos",
        ),
        migrations.DeleteModel(
            name="professores",
        ),
    ]
