# Generated by Django 4.1.7 on 2023-03-21 18:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("classes", "0012_remove_professores_turma_remove_professores_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="turma",
            name="codigo",
            field=models.CharField(max_length=7, unique=True),
        ),
        migrations.CreateModel(
            name="AlunoTurma",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "aluno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "turma",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="classes.turma"
                    ),
                ),
            ],
        ),
    ]
