# Generated by Django 4.1.7 on 2023-03-21 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("classes", "0013_alter_turma_codigo_alunoturma"),
    ]

    operations = [
        migrations.AddField(
            model_name="atividade",
            name="turma",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="classes.turma",
            ),
            preserve_default=False,
        ),
    ]
