# Generated by Django 4.1.7 on 2023-03-23 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("classes", "0015_professor"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Professor",
        ),
    ]
