# Generated by Django 4.1.7 on 2023-03-28 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classes", "0017_professor_alter_atividade_professor_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="atividade",
            name="comentario",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="turma",
            name="descricao",
            field=models.TextField(blank=True),
        ),
    ]
