# Generated by Django 4.1.7 on 2023-03-28 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("classes", "0018_atividade_comentario_alter_turma_descricao"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="atividade",
            name="comentario",
        ),
        migrations.CreateModel(
            name="ComentarioAtividade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comentario", models.TextField()),
                (
                    "atividade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="classes.atividade",
                    ),
                ),
            ],
        ),
    ]
