# Generated by Django 4.1.7 on 2023-03-28 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classes", "0019_remove_atividade_comentario_comentarioatividade"),
    ]

    operations = [
        migrations.AddField(
            model_name="atividade",
            name="comentario",
            field=models.TextField(blank=True),
        ),
    ]
