# Generated by Django 4.1.7 on 2023-03-28 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classes", "0020_atividade_comentario"),
    ]

    operations = [
        migrations.AddField(
            model_name="comentarioatividade",
            name="autor",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
