# Generated by Django 4.1.7 on 2023-04-03 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classes", "0021_comentarioatividade_autor"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="atividade",
            name="comentario",
        ),
        migrations.AlterField(
            model_name="atividade",
            name="data_entrega",
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name="comentarioatividade",
            name="comentario",
            field=models.TextField(default=""),
        ),
    ]
