# Generated by Django 4.1.7 on 2023-04-05 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classes", "0022_remove_atividade_comentario_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="atividade",
            name="concluida",
            field=models.BooleanField(default=False),
        ),
    ]
