# Generated by Django 4.1.7 on 2023-04-05 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classes", "0023_atividade_concluida"),
    ]

    operations = [
        migrations.AddField(
            model_name="atividade",
            name="entregue_com_atraso",
            field=models.BooleanField(default=False),
        ),
    ]
