# Generated by Django 4.1.7 on 2023-04-07 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classes", "0024_atividade_entregue_com_atraso"),
    ]

    operations = [
        migrations.AddField(
            model_name="comentarioatividade",
            name="mostrar_botao_excluir",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="respostaatividade",
            name="arquivo",
            field=models.FileField(blank=True, null=True, upload_to="media/"),
        ),
    ]
