# Generated by Django 4.1.7 on 2023-04-07 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("classes", "0025_comentarioatividade_mostrar_botao_excluir_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comentarioatividade",
            name="mostrar_botao_excluir",
        ),
    ]
